version: '3.8'
services:
  postgres-container:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hammad
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network

  springboot-app:
    image: my-springboot-app
    container_name: springboot-app
    restart: always
    depends_on:
      - postgres-container
      - redis-container
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres-data:
