services:
  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5433:5432"
    networks:
      - command-snippet-api_my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: always
    env_file:
      - .env.prod
    ports:
      - "6379:6379"
    networks:
      - command-snippet-api_my-network

  springboot-app:
    image: my-springboot-app
    container_name: springboot-app
    restart: always
    depends_on:
      - postgres-container
      - redis-container
    env_file:
      - .env.prod 
    ports:
      - "8080:8080"
    networks:
      - command-snippet-api_my-network

networks:
  command-snippet-api_my-network:

volumes:
  postgres-data:
