services:
  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - command-snippet-api_my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: always
    environment:
       REDIS_HOST: ${REDIS_HOST}
       REDIS_PORT: ${REDIS_PORT}
    ports:
      - "6379:6379"
    networks:
      - command-snippet-api_my-network

#  springboot-app:
#    image: my-springboot-app
#    container_name: springboot-app
#    restart: always
#    depends_on:
#      - postgres-container
#      - redis-container
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    ports:
#      - "8080:8080"
#    networks:
#      - command-snippet-api_my-network

networks:
  command-snippet-api_my-network:

volumes:
  postgres-data:
